import "@fontsource/roboto";
import "./globals.css";
import Navbar from "@/components/ui/pure/Navbar";
import ThemeProvider from "@/hooks/useTheme";
import Footer from "@/components/ui/pure/Footer";
import { AuthProvider } from "@/hooks/useAuth";
import NotificationProvider from "@/hooks/useNotification";

export const metadata = {
  title: "Nexa AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="flex flex-col min-h-dvh relative dark:bg-gradient-dark-bg bg-gradient-light-bg overflow-x-hidden">
        <ThemeProvider>
          <NotificationProvider>
            <AuthProvider>
              <Navbar />
              {children}
              <Footer />
            </AuthProvider>
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
