# Imagen base de Python
FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1

# Usar Gunicorn como servidor WSGI
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:create_app()"]